### ISSUE TITLE
VS code doesn't open a new window?

### ISSUE THREAD

**Issue by DB11051998** [abhishekkrthakur/colabcode#16]
whenever i call plt.imshow() along with it when i call plt.show()  it shows output which is shown in the attached screenshot.

![nw1](https://user-images.githubusercontent.com/43936231/92939796-daef1100-f46b-11ea-8fc4-d562e5262c46.png)

is there any solution to this?

**Comment by girishponkiya** [comment]
simple hack: (a) save the image file, and (b) open the image file manually.

**Comment by DB11051998** [comment]
@girishponkiya i know this. But is there anyway to open a new window in the above vscode  using colab server

**Comment by Vijay2051** [comment]
That's running on a server, so new image plot created will be opened in a separate desktop windows right!... so it can't be viewed

**Comment by DB11051998** [comment]
@Vijay2051 thank you!
