### ISSUE TITLE
Unable to access competition data from Kaggle

### ISSUE THREAD

**Issue by kushagrgoyal** [abhishekkrthakur/colabcode#40]
I am not able to access the competition data after logging into the code server.
Are there any additional steps or commands needed to do this? I've followed the tutorial based on the Youtube video.

![image](https://user-images.githubusercontent.com/60442695/98561994-87fcd300-22cf-11eb-8e5f-9bba008e5a55.png)
![image](https://user-images.githubusercontent.com/60442695/98562040-9945df80-22cf-11eb-9402-1a105e887b6d.png)

**Comment by abhishekkrthakur** [comment]
instead of root folder, try kaggle folder!

**Comment by kushagrgoyal** [comment]
Thanks! It works.
