### ISSUE TITLE
Python interpreter depends on unreachable ms-toolsai.jupyter

### ISSUE THREAD

**Issue by MarkB2** [abhishekkrthakur/colabcode#42]
On colab after successful setup and entering VS Code I got 
![fig1](https://user-images.githubusercontent.com/6130988/98973895-faaebe00-251c-11eb-9f70-dbce6e6dfee2.png) 
and after trying to run file 
![fig2](https://user-images.githubusercontent.com/6130988/98974211-524d2980-251d-11eb-8ba6-71a52cc9a54b.png) 
but VS Code couldn't install this extension, it reports it couldn't be found.

The same happens on Kaggle too.   

I used Chrome (86.0.4240.198) and Firefox (82.0.3).

**Comment by abhishekkrthakur** [comment]
for first use "https"
second: fixed

**Comment by MarkB2** [comment]
Thanks
