### ISSUE TITLE
Jupyter: ms-toolsai.jupyter

### ISSUE THREAD

**Issue by jejsemin** [abhishekkrthakur/colabcode#43]
I have been having many problems with this extension

1. I am using this Jupyter notebook as an extension to run my Python ipynb files but every time I go to run it it runs in the console instead of the notebook
2. It is reset to Python instead of Jupyter every time I try to run it. How do I get them to stop returning to Python and stay on the Jupyter setting? 
3. I want to be able to use Python extension without this Jupyter notebook extension as the previous version was much more friendly, how do I do that?
![Screen Shot 2020-11-12 at 2 24 08 PM](https://user-images.githubusercontent.com/63566417/98986631-2ae16700-24f3-11eb-9b69-96413186d562.png)
![Screen Shot 2020-11-12 at 2 27 27 PM](https://user-images.githubusercontent.com/63566417/98986656-33d23880-24f3-11eb-82e5-9ebc87ee8ad1.png)

**Comment by abhishekkrthakur** [comment]
fixed
