### ISSUE TITLE
Jupyer is installed but I can't open a ipynb file with Jupyter in editor

### ISSUE THREAD

**Issue by kevingoh** [abhishekkrthakur/colabcode#54]
ipynb file is opened in text editor by default and re-openning the notebook with Jupyter seems to take forever

**Comment by anusikh** [comment]
This is because the extension failed to activate. I checked the web console and it says:
`abstractExtensionService.ts:717 Cannot activate extension 'Python' because it depends on extension 'ms-toolsai.jupyter', which failed to activate`

**Comment by abhishekkrthakur** [comment]
can you try downgrading python extension to 2020.10.X ?

**Comment by anusikh** [comment]
Yes i did... 
Also tried installing it manually using the VSIX package.

**Comment by kevingoh** [comment]
Yes downgrading the Python extension worked! Thanks
