### ISSUE TITLE
Tunnel dbe97d507087.ngrok.io not found

### ISSUE THREAD

**Issue by giangdip2410** [abhishekkrthakur/colabcode#60]
I just found this issue when connect codeserver using google colab. Anybody have solution for this ? thank you

**Comment by andandandand** [comment]
I am getting the same error on Colab. The server runs on Kaggle notebooks

**Comment by h1psta** [comment]
Same error on Colab...

**Comment by GJvignesh** [comment]
Same error Tunnel <random_alphanumeric>.ngrok.io not found

**Comment by Tyler713** [comment]
I got this output
<Code Server can be accessed on: NgrokTunnel: "http://a3fc17cf4831.ngrok.io" -> "http://localhost:10000">
and i clicked the first link  "http://a3fc17cf4831.ngrok.io"
the chrome told me Tunnel a3fc17cf4831.ngrok.io not found

**Comment by abhishekkrthakur** [comment]
It seems like google colab has been blocking tunnels like ngrok. If I am able to find a workaround, ill implement it. Currently, we wait :(

**Comment by fajarslvn** [comment]
@abhishekkrthakur I don't if this work or not, but it made with python and it similar with ngrok https://github.com/azimjohn/jprq
Maybe it can replace ngrok.

**Comment by abhishekkrthakur** [comment]
Apparently, the issue was on ngrok side and they seem to have resolved it now. I just checked and everything works!

![image](https://user-images.githubusercontent.com/1183441/106567238-cc47ea00-6531-11eb-8ef1-2fe35811fdef.png)

**Comment by Tyler713** [comment]
yes,it works fine on colab now.
thanks a lot

**Comment by h1psta** [comment]
thanks a lot man!
________________________________

**Comment by fajarslvn** [comment]
Thanks Man!

**Comment by andandandand** [comment]
Thanks for checking this!
______________

*Antonio Rueda-Toicen*Data Scientist
digital-spaceti.me

**Comment by giangdip2410** [comment]
thank you so much @abhishekkrthakur

**Comment by abhishekkrthakur** [comment]
I just tested it and it seems to be working fine.
