### ISSUE TITLE
Gpu acceleration not working

### ISSUE THREAD

**Issue by Rizialdi** [abhishekkrthakur/colabcode#61]
Hi Abhishek,

I hope you are fine. I don't know if you are aware of, or if it's just a bug for me, but when a add GPU acceleration to Kaggle or Colab notebooks it no longer works. I think google restricted their use but am not sure.

Are you aware of that it's not possible to have a GPU ?
Do you know a workaround to still use GPU ?

It's so convenient to use vs-code. Thank you in advance.

**Comment by abhishekkrthakur** [comment]
It seems to be working fine for me.

![image](https://user-images.githubusercontent.com/1183441/106567617-65770080-6532-11eb-96c9-6b1d9e6636e6.png)

**Comment by Rizialdi** [comment]
Woow.
It just worked too. I probably did something wrong that day. 
Thank you Abhishek and have a nice day.
Best.
