### ISSUE TITLE
Ngrok Tunnel shows blank screen

### ISSUE THREAD

**Issue by tobiasdr** [abhishekkrthakur/colabcode#65]
Hello,

I have a new problem I have not encountered before with Colabcode and I hope to find help here. I am running 
from google.colab import drive
drive.mount('/content/drive')

!pip install colabcode
from colabcode import ColabCode
ColabCode(port=10000)

in Colab and usually was able to access the Colab VSCode environment with an Ngrok tunnel there (2 weeks ago), however since yesterday it shows a blank screen. The output of the Colab cell is the same as before. Only difference is I get prompted to restart the runtime after which the output is the same as before when it ran smoothly.
Colabcode 0.2.0 was used but same problem persists with colabcode 0.1.0

Code Server can be accessed on: NgrokTunnel: "http://(id).ngrok.io" -> "http://localhost:10000"
[2021-02-04T09:28:44.663Z] info  code-server 3.7.4 (id)
[2021-02-04T09:28:44.664Z] info  Using user-data-dir ~/.local/share/code-server
[2021-02-04T09:28:44.673Z] info  Using config file ~/.config/code-server/config.yaml
[2021-02-04T09:28:44.673Z] info  HTTP server listening on http://127.0.0.1:10000 
[2021-02-04T09:28:44.673Z] info    - Authentication is disabled 
[2021-02-04T09:28:44.673Z] info    - Not serving HTTPS

Does anyone have any idea what the problem could be? Would appreciate any help, many thanks

**Comment by tobiasdr** [comment]
Additional info: colabcode 2.0 was used but same problem persists with colabcode 0.1.0

**Comment by abhishekkrthakur** [comment]
Not sure what the problem is. Seems like a browser/connection issue. Try refreshing the page or opening the ngrok link in incognito mode and see if it works.

BTW, to mount drive you can do this:

`ColabCode(port=10000, mount_drive=True)`

**Comment by tobiasdr** [comment]
Thank you for the quick reply! For some reason it worked on Opera with a VPN, failed on Firefox Chrome, Safari.
