### ISSUE TITLE
Python debugging doesn't work in ColabCode (or in ngrok?)

### ISSUE THREAD

**Issue by krivenkoz** [abhishekkrthakur/colabcode#71]
I'm using amazing ColabCode by Abhishek Thakur. It uses ngrok as backbone. But when I try to debug Python script (via F5 button), it doesn't launch any debug action even when I set a breakpoint. Script runs in terminal only. launch.json is empty. When I fill it with next:

"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "console": "integratedTerminal"
    }        

]
I've got next error:

Couldn't find a debug adapter descriptor for debug type 'python' (extension might have failed to activate)

How can I debug Python script on ngrok code-server?

**Comment by skepsun** [comment]
You can try downgrade python extention to 2020.10

**Comment by krivenkoz** [comment]
Dear Abhishek! Thanks a lot, it helps (but I've installed 2020.5 instead of 2020.10)
