### ISSUE TITLE
Not able to copy paste anything on terminal. 

### ISSUE THREAD

**Issue by SinhaPrateek** [abhishekkrthakur/colabcode#76]
![issue](https://user-images.githubusercontent.com/16855939/111916370-9be7eb00-8aa0-11eb-9012-4190ce8c8fae.PNG)

**Comment by misalraj** [comment]
I don't know how you are doing copy-paste. Use 'ctrl+shift+v' for paste.

**Comment by SinhaPrateek** [comment]
Oh ok. I was doing 'ctrl+v'. Wasn't aware of this. Thanks.
