### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by pratt3000** [abhishekkrthakur/colabcode#84]
Too Many Connections
Too many connections! The tunnel session 'ts_1uRbFxBjU6WBQdMADOpMnFpA5mZ' has violated the rate-limit policy of 20 connections per minute by initiating 31 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702

**Comment by abhishekkrthakur** [comment]
please use auth key from ngrok. register a free account and use that key when using ColabCode.
