### ISSUE TITLE
Blank Screen on Run

### ISSUE THREAD

**Issue by attacker007** [abhishekkrthakur/colabcode#85]
Hi,

Recently whenever i have tried to use and Run the Collab ... then i go to *.ngrok.io site... It does not show any thing after login page.... I've tried in multiple browsers... 

Can anyone check ?

**Comment by astorfi** [comment]
@attacker007 I have the same issue.

**Comment by rohitar** [comment]
Yup - experiencing the same issue since a week or so. Could someone please advise how this can be resolved?

**Comment by vjagannath786** [comment]
Same issue....

**Comment by ceo** [comment]
Same here, i think ngrok is the issue.. its possible to use:

from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(10000)"))

instead of ngrok ?

**Comment by Tirbo06** [comment]
Same issue.. 
- with *.ngrok i get a empty page 
- with the 127.0.0.1:10000 i get a "connexion failed"

**Comment by FeryET** [comment]
Same issue here. I think ngrok has restricted the free use of its service.

**Comment by abhishekkrthakur** [comment]
I just tested it and it seems to be working fine with and without auth_key from ngrok. there are no issues. please try clearing cache. if mounting drive, you need to wait for a bit for session to start.
