### ISSUE TITLE
Starting with `mount_drive=True` hangs startup

### ISSUE THREAD

**Issue by gbraad** [abhishekkrthakur/colabcode#86]
When the option to mount the drive is specified;

```
ColabCode(port=10000, password="pass", authtoken="[ngroktoken]", mount_drive=True)
```

... it will only start as:

```
Code Server can be accessed on: NgrokTunnel: "https://[tunnelid[.ngrok.io" -> "http://localhost:10000"
```

... and just hang. Any idea?

**Comment by gbraad** [comment]
Actually;

```
ColabCode(port=10000, password="pass", authtoken="[ngroktoken]", mount_drive=False, lab=True)
```

does the same. It does start JupyterLab, but prevents Code from starting as that process needs to be active and long-running.

**Comment by abhishekkrthakur** [comment]
I just tested it and it seems to be working fine. when mounting drive, you need to click on the link that is presented to you then authorize the colab to access drive and wait till its done mounting.
