### ISSUE TITLE
ngrok requires registration

### ISSUE THREAD

**Issue by joeleonard212** [abhishekkrthakur/colabcode#98]
Hi there, I was happily using ColabCode 'till yesterday

Today this show up

![Screenshot_20211208_012346](https://user-images.githubusercontent.com/35630044/145126432-396bc889-5614-4e50-b748-40362f95f70d.png)

Someone knows some workaround ? I tried to put the ngrok.yml file with my authcode in the VM hosting the Colab but it doesnt seem to work

**Comment by joeleonard212** [comment]
OK in the ColabCode's code, just found out the authtoken parameter

Sorry for the useless question, the description in the home was not very complete about this :)

Thanks

**Comment by finquick** [comment]
I meet the same problem, what should I do? what's wrong with it?

**Comment by finquick** [comment]
I see!
just goto the site by link, and get Your Authtoken, then before ColabCode(port=8888, mount_drive=True) run command  :ngrok authtoken **********   in colab!

**Comment by joeleonard212** [comment]
you can actually just add a parameter in the class:

ColabCode(port=1010, mount_drive=True, authcode='{yourauthcodehere}'

**Comment by yucongo** [comment]
I think this issue shouldn't be closed. In fact, this should be in readme.md?

**Comment by m-ali-awan** [comment]
Thanks for the solution.

**Comment by akuz0** [comment]
> you can actually just add a parameter in the class:
> 
> ColabCode(port=1010, mount_drive=True, authcode='{yourauthcodehere}'

For me solution, use authtoken
ColabCode(port=1010, authtoken='key')
