### ISSUE TITLE
Can't access VSCode Server via GoogleColab and Kaggle

### ISSUE THREAD

**Issue by longqua69** [abhishekkrthakur/colabcode#99]
Hi,

This is a really helpful project. However, I've tried using this and got an unexpected behavior after clicking the link in the figure below:
![1](https://user-images.githubusercontent.com/37626565/146782647-5d3266c7-5557-42c9-a3da-5e25fe2acb2d.PNG)
- My browser was navigated to:
![2-colabcode](https://user-images.githubusercontent.com/37626565/146782819-68372519-788b-4ca0-ba69-3cf485a17c9f.PNG)
- I tried signing up with my Google account then I navigate to:
![3](https://user-images.githubusercontent.com/37626565/146782920-771c9da3-5593-422a-99c4-785fc2f41c33.PNG)

The same issue occurred while using GoogleColab. I can't access VSCode Server. Please help me fix this issue or let me know if I've missed something

Thanks

**Comment by abhishekkrthakur** [comment]
After registering a new account, you can pass your authentication token in the `authtoken` parameter and everything should be fine.

**Comment by longqua69** [comment]
Hi @abhishekkrthakur 

Thanks, I followed your instructions by:
1. Download ngrok
2. Pass `authtoken` into ngrok CLI
3. Executed the command `ngrok HTTP 80`

Below is the result. What should I do next? Is there any step that I've missed?
![image](https://user-images.githubusercontent.com/37626565/146801991-5329dc1e-1c13-4eb5-a1e7-5f275917e5bf.png)

**Comment by TakshPanchal** [comment]
> 2. Pass `authtoken` into ngrok CLI

You are supposed to do this on colab.

**Comment by longqua69** [comment]
@TakshPanchal thank you so much.
